version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- channel_presence

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: server.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/venv/.*$
